name: Publish Package

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    if: github.repository == 'vectara/py-vectara-agentic'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine pytest flake8

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Run tests
      run: |
        pytest --disable-warnings

    - name: Check installation
      run: |
        pip install dist/*.whl

    - name: Lint the package
      run: |
        flake8 --ignore=E501 .

    - name: Publish package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        twine upload dist/*
        